### ISSUE TITLE
Postal.EmailViewResult.ExecuteResultAsync - Headers are read-only, response has already started

### ISSUE THREAD

**Issue by emouawad** [hermanho/postal.aspnetcore#15]
EmailViewResult writing to the response throwing the following exception

https://github.com/hermanho/postal.aspnetcore/blob/eff8c969c93ec5a5f19f5b987d7928bfdb9f1f6e/src/Postal.AspNetCore/EmailViewResultExecutor.cs#L70

Btw using Razor Pages on ASP Core 3.1

``` csharp 
   public class IndexModel : PageModel
    {
        public IActionResult OnGet()
        {
            return new EmailViewResult(new NotificationEmail
            {
                //ViewName = "NotificationEmail.cshtml",
                ViewName = "/Pages/Emails/NotificationEmail.cshtml",
            });
        }
    }

System.InvalidOperationException: Headers are read-only, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_ContentType(String value)
   at Postal.AspNetCore.EmailViewResultExecutor.ExecuteAsync(ActionContext context, EmailViewResult result)
   at Postal.EmailViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at StackExchange.Redis.Extensions.AspNetCore.Midllewares.RedisInformationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by hermanho** [comment]
Please share a testing project. Why you need EmailViewResult at there? Have you tried with the sample repo?

**Comment by emouawad** [comment]
The EmailViewResult in the original code base was a useful feature to render the email as a view that can be used to preview the email while developing / testing - for faster layout changes. I see it isn't documented in the aspnetcore version is this a bug (not ported to core) or there is another way to do it? Again what i am trying to do is to render the email as a normal view inside PageModel

**Comment by hermanho** [comment]
I tried with PageModel and no error throwed. You can refer to the sample repo

https://github.com/hermanho/postal.aspnetcore.samples

**Comment by emouawad** [comment]
Hi thanks for adding the Pages sample code. I have copied your example to my project and still same exception.
My whole app is working as expected - only Postal is failing.
And that's clear in the log dump i have previously included: the issue is when trying to directly set the response content type explicitly and not using a middleware to do that - I have seen this somewhere else with core - my guess it's not visible in the sample app because it's too simple: with middlewares that can write to the response it should appear.

Would it be possible to disable with some flag the autodetection of the type text/html therefore disabling the header set? or maybe set type from the beginning at initialization. 
In most cases an email is either text or html and that's known at design time, i don't see the added benefit of having that dynamic anyway but i can be wrong.

**Comment by hermanho** [comment]
Please share a minimal repository for reproducing issues.

Assign the response headers and content type are quite common in the IActionResultExecutor.
For examples:
https://github.com/dotnet/aspnetcore/blob/76ffbeecd666594e5fc292e4ad230adff55c6329/src/Mvc/Mvc.Core/src/Infrastructure/ContentResultExecutor.cs#L53
https://github.com/dotnet/aspnetcore/blob/76ffbeecd666594e5fc292e4ad230adff55c6329/src/Mvc/Mvc.Core/src/Infrastructure/RedirectResultExecutor.cs#L70
https://github.com/dotnet/aspnetcore/blob/adf7a08fadbedec5431e680ca28da73648229770/src/Mvc/Mvc.ViewFeatures/src/ViewExecutor.cs#L227

I think the problem is why the response has already started before everything are done.
